name: robopy
channels:
 - conda-forge
dependencies:
 - ipyvolume==0.5.1
 - ipywidgets>=7.4.0
 - ipywebrtc>=0.4
 - pip:
   - matplotlib
   - Pillow
   - scipy
   - numpy
   - requests
   - scikit-image>=0.13
- notebook>=5.3
