name: py35_ipynb
channels:
  - conda-forge
dependencies:
  - python=3.5
  - ipyvolume==0.5.1
  - ipywidgets>=7.4.0
  - ipywebrtc>=0.4
  - pip:
      - matplotlib>=3
      - Pillow
      - imageio
      - numpy
      - numpy-stl
      - scipy
      - scikit-image>=0.13
      - requests
      - notebook>=5.3
      - vtk
      - xvfbwrapper
